version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root         # ✅ necessário para inicializar o MySQL
      MYSQL_DATABASE: inf25dw2g07
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"                     # 3307 externo (host), 3306 interno (container)
    volumes:
      - mysql_data:/var/lib/mysql

  nodeapp:
    build: .
    container_name: node_app_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && node server.js"
    environment:
      DB_HOST: mysql                   #  nome do serviço MySQL
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: inf25dw2g07
      DB_PORT: 3306                    # use sempre a porta interna aqui!

volumes:
  mysql_data:

